twig:
    form:
        resources:
            - 'TmsFormGeneratorBundle:Form:fields.html.twig'

tms_form_generator:
    form_field_types:
        form:
            abstract: true
            type: form
            options:
                label: {"type": "text", "options": {"required": false}}
                required: {"type": "toggle_button", "options": {"required": false}}
                disabled: {"type": "toggle_button", "options": {"required": false}}
                read_only: {"type": "toggle_button", "options": {"required": false}}
                data: {"type": "text", "options": {"required": false}}
                attr: {"type": "text", "options": {"required": false}}
                help: {"type": "textarea", "options": {"required": false}}

        text:
            parent: form
            type: text
            alias: "Champ de saisie texte"
            options:
                max_length: {"type": "number", "options": {"required": false}}
                trim: {"type": "toggle_button", "options": {"required": false}}

        regexp:
            parent: text
            type: text
            alias: "Champ de saisie texte avec expression régulière"
            options:
                pattern: {"type": "text", "options": {"required": false}}

        textarea:
            parent: form
            type: textarea
            alias: "Zone de saisie texte"
            options:
                max_length: {"type": "number", "options": {"required": false}}
                trim: {"type": "toggle_button", "options": {"required": false}}

        email:
            parent: regexp
            type: email
            alias: "Champ de saisie couriel (email)"

        url:
            parent: regexp
            type: url
            alias: "Champ de saisie adresse URL"
            options:
                default_protocol: {"type": "choice", "options": {"choices": {"http": "http", "https": "https"}}}

        integer:
            parent: form
            type: integer
            alias: "Champ de saisie nombre entier"
            options:
                precision: {"type": "number", "options": {"required": false, "data": 2}}

        money:
            parent: form
            type: money
            alias: "Champ de saisie valeur monaitaire"
            options:
                currency: {"type": "text", "options": {"required": false, "data": "EUR"}}
                precision: {"type": "number", "options": {"required": false, "data": 2}}

        number:
            parent: form
            type: number
            alias: "Champ de saisie nombre décimal"
            options:
                precision: {"type": "number", "options": {"required": false, "data": 2}}

        password:
            parent: text
            type: password
            alias: "Champ de saisie de mot de passe"
            options:
                always_empty: {"type": "toggle_button", "options": {"required": false}}

        percent:
            parent: form
            type: percent
            alias: "Champ de saisie pourcentage"
            options:
                type: {"type": "text", "options": {"required": false}}
                precision: {"type": "number", "options": {"required": false, "data": 0}}

        choice:
            parent: form
            type: choice
            alias: "Champ de sélection"
            options:
                choices: {"type": "text", "options": {"required": false}}
                multiple: {"type": "toggle_button", "options": {"required": false}}
                expanded: {"type": "toggle_button", "options": {"required": false}}
                preferred_choices: {"type": "text", "options": {"required": false}}
                empty_value: {"type": "text", "options": {"required": false}}

        date:
            parent: form
            type: date
            alias: "Champ de saisie de date"
            options:
                format: {"type": "text", "options": {"data": "dd-MM-yyyy"}}
                widget: {"type": "choice", "options": {"choices": {"choice": "Affiche trois listes déroulantes. L'ordre des listes est défini par l'option format", "text": "Affiche trois champs textes (mois, jour, année)", "single_text": "Affiche un unique champ texte. La saisie de l'utilisateur sera validé en se basant sur l'option format"}, "data": "choice"}}
                input: {"type": "choice", "options": {"choices": {"string": "string", "datetime": "datetime", "array": "array", "timestamp": "timestamp"}, "data": "datetime"}}
                years: {"type": "text", "options": {"required": false}}
                months: {"type": "text", "options": {"required": false}}
                days: {"type": "text", "options": {"required": false}}
                empty_value: {"type": "text", "options": {"required": false}}

        time:
            parent: form
            type: time
            alias: "Champ de saisie d'horaires"
            options:
                widget: {"type": "choice", "options": {"choices": {"choice": "Rend deux (ou trois si with_seconds est à true) listes déroulantes", "text": "Rend deux ou trois champs input texte (heures, minutes, secondes)", "single_text": "Rend un simple input texte"}, "data": "choice"}}
                input: {"type": "choice", "options": {"choices": {"string": "string", "datetime": "datetime", "array": "array", "timestamp": "timestamp"}, "data": "datetime"}}
                with_seconds: {"type": "toggle_button", "options": {"required": false}}
                hours: {"type": "text", "options": {"required": false}}
                minutes: {"type": "text", "options": {"required": false}}
                seconds: {"type": "text", "options": {"required": false}}
                empty_value: {"type": "text", "options": {"required": false}}

        datetime:
            parent: form
            type: datetime
            alias: "Champ de saisie de date et horaires"
            options:
                date_format: {"type": "text", "options": {"data": "dd-MM-yyyy"}}
                date_widget: {"type": "choice", "options": {"choices": {"choice": "Affiche trois listes déroulantes. L'ordre des listes est défini par l'option format", "text": "Affiche trois champs textes (mois, jour, année)", "single_text": "Affiche un unique champ texte. La saisie de l'utilisateur sera validé en se basant sur l'option format"}, "data": "choice"}}
                time_widget: {"type": "choice", "options": {"choices": {"choice": "Rend deux (ou trois si with_seconds est à true) listes déroulantes", "text": "Rend deux ou trois champs input texte (heures, minutes, secondes)", "single_text": "Rend un simple input texte"}, "data": "choice"}}
                input: {"type": "choice", "options": {"choices": {"string": "string", "datetime": "datetime", "array": "array", "timestamp": "timestamp"}, "data": "datetime"}}
                years: {"type": "text", "options": {"required": false}}
                months: {"type": "text", "options": {"required": false}}
                days: {"type": "text", "options": {"required": false}}
                hours: {"type": "text", "options": {"required": false}}
                minutes: {"type": "text", "options": {"required": false}}
                seconds: {"type": "text", "options": {"required": false}}
                with_seconds: {"type": "toggle_button", "options": {"required": false}}
                empty_value: {"type": "text", "options": {"required": false}}

        birthday:
            parent: date
            type: birthday
            alias: "Champ de saisie de date d'anniversaire"

        checkbox:
            parent: form
            type: checkbox
            alias: "Champ de saisie boolean (checkbox)"
            options:
                value: {"type": "text", "options": {"required": false}}

        toggle_button:
            parent: form
            type: toggle_button
            alias: "Champ de sélection binaire (Off/On)"
            options:
                choices: {"type": "text", "options": {"required": false}}

        iban:
            parent: form
            type: iban
            alias: "Champ de saisie IBAN"

        imei:
            parent: text
            type: imei
            alias: "Champ de saisie IMEI"

        html_text:
            type: html_text
            alias: "Texte HTML"
            options:
                content: {"type": "textarea", "options": {"required": false}}

        captcha:
            parent: text
            type: captcha
            alias: "Champ de contrôle humain (CAPTCHA)"
            options:
                width: {"type": "number", "options": {"required": false, "data": 120}}
                height: {"type": "number", "options": {"required": false, "data": 40}}
                length: {"type": "number", "options": {"required": false, "data": 5}}
                quality: {"type": "number", "options": {"required": false, "data": 15}}
                charset: {"type": "text", "options": {"required": false, "data": "abcdefhijklmnopqrstuvwxyz0123456789"}}
                keep_value: {"type": "toggle_button", "options": {"required": false, "data": "1"}}
                as_file: {"type": "toggle_button", "options": {"required": false}}
                as_url: {"type": "toggle_button", "options": {"required": false}}
                invalid_message: {"type": "text", "options": {"required": false, "data": "Bad code value"}}
                bypass_code: {"type": "text", "options": {"required": false}}
                whitelist_key: {"type": "text", "options": {"required": false, "data": "captcha_whitelist_key"}}
                reload: {"type": "toggle_button", "options": {"required": false}}
                humanity: {"type": "number", "options": {"required": false, "data": 0}}
                distortion: {"type": "toggle_button", "options": {"required": false, "data": "1"}}
                max_front_lines: {"type": "number", "options": {"required": false}}
                interpolation: {"type": "toggle_button", "options": {"required": false}}

        hidden:
            parent: form
            type: hidden
            alias: "Champ invisible"
