services:
    tms_form_generator.form.type.form_field:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldType
        tags:
            - { name: form.type, alias: form_field }

    tms_form_generator.form.type.form_fields:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldsType
        tags:
            - { name: form.type, alias: form_fields }

twig:
    form:
        resources:
            - 'TmsFormGeneratorBundle:Form:fields.html.twig'
