twig:
    form:
        resources:
            - 'TmsFormGeneratorBundle:Form:fields.html.twig'

tms_form_generator:
    form_field_types:
        form:
            abstract: true
            type: form
            options:
                - required: {"type": "checkbox"}
                - disabled: {"type": "checkbox", "options": {"data": false}}
                - attr: {"type": "text"}
                - label: {"type": "text"}

        text:
            parent: form
            type: text
            options:
                - max_length: {"type": "number"}
                - trim: {"type": "checkbox", "options": {"data": true}}
                - read_only: {"type": "checkbox"}

        textarea:
            parent: form
            type: textarea
            options:
                - max_length: {"type": "number"}
                - trim: {"type": "checkbox", "options": {"data": true}}

        email:
            parent: form
            type: email
            options:
                - max_length: {"type": "number"}
                - trim: {"type": "checkbox", "options": {"data": true}}

        integer:
            parent: form
            type: integer
            options:
                - precision: {"type": "number", "options": {"data": 2}}

        money:
            parent: form
            type: money
            options:
                - currency: {"type": "text", "options": {"data": "EUR"}}
                - precision: {"type": "number", "options": {"data": 2}}

        number:
            parent: form
            type: number
            options:
                - precision: {"type": "number", "options": {"data": 2}}

        password:
            parent: text
            type: password
            options:
                - always_empty: {"type": "checkbox", "options": {"data": true}}

        percent:
            parent: form
            type: percent
            options:
                - type: {"type": "text"}
                - precision: {"type": "number", "options": {"data": 0}}

        search:
            parent: text
            type: search

        url:
            parent: text
            type: url
            options:
                - default_protocol: {"type": "text", "options": {"data": "http"}}

        date:
            parent: form
            type: date
            options:
                - widget: {"type": "radio", "options": {"choices": ["choice", "text", "single_text"]}}

        birthday:
            parent: date
            type: birthday
            options:
                - years: {"type": "text"}

        checkbox:
            parent: form
            type: checkbox
            options:
                - value: {"type": "text"}

        file:
            parent: form
            type: file

        radio:
            parent: form
            type: radio
            options:
                - value: {"type": "text"}

        hidden:
            parent: form
            type: hidden
