twig:
    form:
        resources:
            - 'TmsFormGeneratorBundle:Form:fields.html.twig'

tms_form_generator:
    form_field_types:
        form:
            abstract: true
            type: form
            options:
                label: {"type": "text", "options": {"required": false}}
                required: {"type": "switch_checkbox", "options": {"required": false}}
                disabled: {"type": "switch_checkbox", "options": {"required": false, "data": false}}
                attr: {"type": "text", "options": {"required": false}}
                data: {"type": "text", "options": {"required": false}}

        text:
            parent: form
            type: text
            options:
                max_length: {"type": "number", "options": {"required": false}}
                trim: {"type": "switch_checkbox", "options": {"required": false, "data": true}}
                read_only: {"type": "switch_checkbox", "options": {"required": false}}

        textarea:
            parent: form
            type: textarea
            options:
                max_length: {"type": "number", "options": {"required": false}}
                trim: {"type": "switch_checkbox", "options": {"required": false, "data": true}}

        email:
            parent: form
            type: email
            options:
                max_length: {"type": "number", "options": {"required": false}}
                trim: {"type": "switch_checkbox", "options": {"required": false, "data": true}}

        integer:
            parent: form
            type: integer
            options:
                precision: {"type": "number", "options": {"required": false, "data": 2}}

        money:
            parent: form
            type: money
            options:
                currency: {"type": "text", "options": {"required": false, "data": "EUR"}}
                precision: {"type": "number", "options": {"required": false, "data": 2}}

        number:
            parent: form
            type: number
            options:
                precision: {"type": "number", "options": {"required": false, "data": 2}}

        password:
            parent: text
            type: password
            options:
                always_empty: {"type": "switch_checkbox", "options": {"required": false, "data": true}}

        percent:
            parent: form
            type: percent
            options:
                type: {"type": "text", "options": {"required": false}}
                precision: {"type": "number", "options": {"required": false, "data": 0}}

        search:
            parent: text
            type: search

        url:
            parent: text
            type: url
            options:
                default_protocol: {"type": "text", "options": {"required": false, "data": "http"}}

        date:
            parent: form
            type: date
            options:

        birthday:
            parent: date
            type: birthday
            options:
                years: {"type": "text", "options": {"required": false}}

        checkbox:
            parent: form
            type: checkbox
            options:
                value: {"type": "text", "options": {"required": false}}

        file:
            parent: form
            type: file

        radio:
            parent: form
            type: radio
            options:
                value: {"type": "text", "options": {"required": false}}

        hidden:
            parent: form
            type: hidden
