parameters:
    tms_form_generator.generator.builder.class: Tms\Bundle\FormGeneratorBundle\Generators\FormBuilderGenerator

services:
    tms_form_generator.generator.default:
        class:     %tms_form_generator.generator.builder.class%
        arguments: [@form.factory, null]
        abstract:  true

    tms_form_generator.form.type.form_field:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldType
        tags:
            - { name: form.type, alias: form_field }

    tms_form_generator.form.type.form_fields:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldsType
        tags:
            - { name: form.type, alias: form_fields }

    tms_form_generator.form_field:
        class: Tms\Bundle\FormGeneratorBundle\Form\FieldType\FormFieldType
        abstract: true
        arguments: [null, null, null]

    tms_form_generator.form.type.form_field_type_choice:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldTypeChoiceType
        arguments: [%tms_form_generator.form_field_types%]
        tags:
            - { name: form.type, alias: form_field_type_choice }

    tms_form_generator.form.type.form_field_options:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldOptionsType
        tags:
            - { name: form.type, alias: form_field_options }

    tms_form_generator.form.type.form_field_constraints:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldConstraintsType
        tags:
            - { name: form.type, alias: form_field_constraints }

    tms_form_generator.form.type.form_field_eligibility:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldEligibilityType
        tags:
            - { name: form.type, alias: form_field_eligibility }
