parameters:
    tms_form_generator.form_builder_generator.class: Tms\Bundle\FormGeneratorBundle\Generators\FormBuilderGenerator

services:
    tms_form_generator.form_builder_generator:
        class:     %tms_form_generator.form_builder_generator.class%
        arguments: [@form.factory, %tms_form_generator.form_field_types%]

    tms_form_generator.form_field:
        class: Tms\Bundle\FormGeneratorBundle\Form\FieldType\FormFieldType
        abstract: true
        arguments: [null, null, null]

    form.type.toggle_button:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\ToggleButtonType
        tags:
            - { name: form.type, alias: toggle_button }

    tms_form_generator.form.type.form_field:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldType
        tags:
            - { name: form.type, alias: form_field }

    tms_form_generator.form.type.form_fields:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldsType
        tags:
            - { name: form.type, alias: form_fields }

    tms_form_generator.form.type.indexed_form_fields:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\IndexedFormFieldsType
        tags:
            - { name: form.type, alias: indexed_form_fields }

    tms_form_generator.form.type.form_field_type_choice:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldTypeChoiceType
        arguments: [%tms_form_generator.form_field_types%]
        tags:
            - { name: form.type, alias: form_field_type_choice }

    tms_form_generator.form.type.form_field_options:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldOptionsType
        tags:
            - { name: form.type, alias: form_field_options }

    tms_form_generator.form.type.form_field_constraints:
        class: Tms\Bundle\FormGeneratorBundle\Form\Type\FormFieldConstraintsType
        tags:
            - { name: form.type, alias: form_field_constraints }
